version: "3.8"

services:
  app:
    build: .
    container_name: intranet_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=intranet
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=intranet
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: intranet_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intranet
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
