version: "3.8"

services:
  app:
    build: .
    container_name: intranet_app
    ports:
      - "3000:3000"  # Altere o primeiro número se quiser acessar por outra porta (ex: "4000:3000")
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=intranet
    depends_on:
      - db
    command: sh -c "sleep 10 && npm run start"
    restart: always

  db:
    image: mysql:8.0
    container_name: intranet_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intranet
    ports:
      - "3307:3306"   # Acesse via localhost:3307 fora do Docker
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
